Controllers-films-users
Elen-B/java-filmorate pull request #5
Opened 2024-06-13 06:55 UTC by Elen-B

2024-06-13 19:15 UTC, z8q requested changes

2024-06-13 19:15 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody(required = false) Film newFilm, BindingResult binding) throws BindException {
На этом этапе допустимо использовать BindingResult, но в последующих домашках лучше создать exception handler и обрабатывать исключения через него
Если убрать второй аргумент метода и оставить только
```
update(@Valid @RequestBody(required = false) Film newFilm)
```
исключения при передаче невалидных данных все равно будут возникать

2024-06-13 19:15 UTC, z8q commented on pom.xml
> +		</dependency>
Есть ли необходимость явно указывать зависимости связанные с логированием?
В spring boot стартере они должны быть включены

2024-06-13 19:32 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email
Аннотация Email допускает null value, можно еще добавить notnull

2024-06-14 03:19 UTC, Elen-B commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody(required = false) Film newFilm, BindingResult binding) throws BindException {
Спасибо! поизучаю тему про exception handler 👌🏻

2024-06-14 19:44 UTC, z8q approved these changes

2024-06-15 03:10 UTC, merged