add-friends-likes
Elen-B/java-filmorate pull request #6
Opened 2024-06-28 05:00 UTC by Elen-B

2024-06-28 22:06 UTC, z8q requested changes

2024-06-28 22:06 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +        //log.error("film update: id is not found");
Закомментированные строки стоит убрать

2024-06-29 03:39 UTC, Elen-B commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody(required = false) Film newFilm) {
убрала required, идея вообще была в том, чтобы на пустой body был ответ 400, а если специально не обрабатывать, то автоматом 500, вроде как такой код немного не про то

2024-06-29 13:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody(required = false) Film newFilm) {
500 возвращается, потому что исключение HttpMessageNotReadableException проходит через этот хендлер
```JAVA
    @ExceptionHandler
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public ErrorResponse handleThrowable(final Throwable e) {
        log.error("handleThrowable: {}", e.getMessage());
        return new ErrorResponse(
                e.getMessage()
        );
    }
```

2024-06-29 13:03 UTC, z8q approved these changes

2024-06-30 09:22 UTC, Elen-B commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody(required = false) Film newFilm) {
поняла, спасибо!

2024-07-01 06:56 UTC, merged